const fs = require('fs');
const portalHtml = fs.readFileSync('src/app/portal.html', 'utf-8');
const lines = portalHtml.split('\n');
const start = lines.findIndex(l => l.includes('<!-- ================= VIEW 3: PRODUCT DETAIL (DYNAMIC PAGE) ================= -->'));
const end = lines.findIndex(l => l.includes('<!-- ================= VIEW 4: PROCESS CHECKOUT / CHECKUP ================= -->'));
const detailLines = lines.slice(start + 1, end).join('\n');

let code = '';
code += 'import { Component, Input, Output, EventEmitter } from "@angular/core";\n';
code += 'import { CommonModule } from "@angular/common";\n';
code += 'import { Product } from "../../portal";\n\n';
code += '@Component({\n';
code += '  selector: "app-product-detail-page",\n';
code += '  standalone: true,\n';
code += '  imports: [CommonModule],\n';
code += '  template: `\n' + detailLines.replace(/`/g, '\\`') + '\n`\n';
code += '})\n';
code += 'export class ProductDetailPageComponent {\n';
code += '  Math = Math;\n';
code += '  @Input() isCinematicGlow = true;\n';
code += '  @Input() product: any;\n';
code += '  @Input() selectedVariantObj: any;\n';
code += '  @Input() dynamicReviews: any[] = [];\n';
code += '  @Input() ratingBreakdown: any[] = [];\n';
code += '  @Input() recommendationPercent: string = "98.4";\n';
code += '  @Input() wishlist: string[] = [];\n';
code += '  @Input() selectedVariantId: string | null = null;\n';
code += '  @Input() selectedGalleryImage: string | null = null;\n';
code += '  @Input() expandedAccordion: string | null = null;\n';
code += '  @Input() selectedPerspectiveIndex = 0;\n\n';
code += '  @Output() navigate = new EventEmitter<string>();\n';
code += '  @Output() addToCart = new EventEmitter<any>();\n';
code += '  @Output() toggleWishlistEvent = new EventEmitter<{id: string, event: MouseEvent}>();\n';
code += '  @Output() selectedVariantIdChange = new EventEmitter<string | null>();\n';
code += '  @Output() selectedGalleryImageChange = new EventEmitter<string | null>();\n';
code += '  @Output() expandedAccordionChange = new EventEmitter<string | null>();\n';
code += '  @Output() selectedPerspectiveIndexChange = new EventEmitter<number>();\n\n';
code += '  isInWishlist(id: string): boolean {\n';
code += '    return this.wishlist.includes(id);\n';
code += '  }\n\n';
code += '  formatPrice(value: number): string {\n';
code += '    if (value == null) return "";\n';
code += '    const parts = value.toFixed(2).split(".");\n';
code += '    const integerPart = parts[0].replace(/\\B(?=(\\d{3})+(?!\\d))/g, ".");\n';
code += '    const decimalPart = parts[1];\n';
code += '    if (decimalPart === "00") return "$ " + integerPart;\n';
code += '    return "$ " + integerPart + "," + decimalPart;\n';
code += '  }\n\n';
code += '  parseBadge(badge: string): string {\n';
code += '    if (!badge) return "";\n';
code += '    if (badge.startsWith("{") && badge.endsWith("}")) {\n';
code += '      try {\n';
code += '        const parsed = JSON.parse(badge);\n';
code += '        return parsed.value ? parsed.value : badge;\n';
code += '      } catch (e) { return badge; }\n';
code += '    }\n';
code += '    return badge;\n';
code += '  }\n\n';
code += '  setView(view: string) { this.navigate.emit(view); }\n';
code += '  toggleWishlist(id: string, event: MouseEvent) { this.toggleWishlistEvent.emit({id, event}); }\n';
code += '  toggleAccordion(section: string) { this.expandedAccordionChange.emit(this.expandedAccordion === section ? null : section); }\n';
code += '}\n';

fs.writeFileSync('src/app/components/pages/product-detail-page.component.ts', code);
console.log('Created ProductDetailPageComponent');
